// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {
    DB: D1Database;
    R2: R2Bucket;
    POSTS_RL: any;
    ATTACHMENT_RL: any;
    EN_SECRET: string;
    JWT_SECRET: string;
    ENVIRONMENT: string;
    WS_SECRET: string;
    WEBSOCKET_URL: string;
    SYSTEM: string;
    CLIENT_ID: string;
    CLIENT_SECRET: string;
    EMAIL_API: string;
}
