// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {
    DB: D1Database;
    R2: R2Bucket;
    JWT_SECRET: string;
}
