name = "uaeu-hub-api"
main = "./src/index.ts"
compatibility_date = "2024-09-25"
compatibility_flags = ["nodejs_compat"]

routes = [
	{ pattern = "api.talente.dev", custom_domain = true }
]

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
