CREATE TABLE IF NOT EXISTS users (
  username TEXT PRIMARY KEY,
  displayname TEXT NOT NULL,
  email TEXT NOT NULL,
  created_at INTEGER NOT NULL DEFAULT CURRENT_TIMESTAMP,
  bio TEXT,
  pfp TEXT
);

CREATE TABLE IF NOT EXISTS posts (
	post_id INTEGER PRIMARY KEY AUTOINCREMENT,
	author TEXT NOT NULL,
	content TEXT NOT NULL,
	post_time INTEGER NOT NULL DEFAULT CURRENT_TIMESTAMP,
	likes INTEGER DEFAULT 0,
	FOREIGN KEY (author) REFERENCES users(username)
);

CREATE TABLE IF NOT EXISTS comments (
	comment_id INTEGER PRIMARY KEY AUTOINCREMENT,
	parent_post_id INTEGER NOT NULL,
	author TEXT NOT NULL,
	content TEXT NOT NULL,
	post_time INTEGER NOT NULL DEFAULT CURRENT_TIMESTAMP,
	likes INTEGER DEFAULT 0,
	FOREIGN KEY (parent_post_id) REFERENCES posts(post_id),
	FOREIGN KEY (author) REFERENCES users(username)
);

