name: WebSocket Server Build Check

on:
    push:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up env
              uses: actions/setup-node@v4
              with:
                  node-version: '22.12.0'
                  cache: 'npm'
                  cache-dependency-path: ./websocket-server/package-lock.json

            - name: Install dependencies
              working-directory: ./websocket-server
              run: npm ci

            - name: Run build
              working-directory: ./websocket-server
              run: tsc
