name: WebSocket Server Build Check

on:
    push:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Set up env
              uses: actions/setup-node@v3
              with:
                  node-version: '18'

            - name: Install dependencies
              working-directory: ./websocket-server
              run: npm install

            - name: Run build
              working-directory: ./websocket-server
              run: tsc
